name: Tests

on:
  push:
    branches: ['**']
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  phpunit:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        php: [8.5, 8.4, 8.3, 8.2]
        os: [ubuntu-latest, windows-latest]
        dependencies: [prefer-lowest, prefer-stable]

    name: PHP ${{ matrix.php }} - ${{ matrix.os }} - ${{ matrix.dependencies }}

    steps:
      - uses: actions/checkout@v7

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, mbstring, xml, xmlwriter
          coverage: none
          tools: composer:v2

      - uses: actions/cache@v6
        with:
          path: ~/.composer/cache/files
          key: composer-${{ runner.os }}-${{ matrix.php }}-${{ matrix.dependencies }}-${{ hashFiles('composer.json') }}

      - run: composer update --${{ matrix.dependencies }} --prefer-dist --no-interaction --no-progress
      - run: composer test
